In [2]:
import pandas as pd
import numpy as np

# VS Code 사용법

In [17]:
pd.set_option('display.max_columns', None)

In [28]:
# 단양 텍스트 파일을 데이터프레임으로 불러오기
df = pd.read_csv('230302_단양_GGP_6-1차_378ea_analysis_FinalReport_top15.txt', sep='\t', encoding='utf-8', skiprows=9, header=0, on_bad_lines='skip')
df.head()

,Sample ID,Sample Name,Sample Index,Sample Group,SNP Name,SNP Index,SNP,SNP Aux,Chr,Position,Allele1 - AB,Allele2 - AB,Allele1 - Forward,Allele2 - Forward,Allele1 - Top,Allele2 - Top,Allele1 - Design,Allele2 - Design,Allele1 - Plus,Allele2 - Plus,X,Y,X Raw,Y Raw,R,Theta,GC Score,Log R Ratio,B Allele Freq,GT Score,Cluster Sep,ILMN Strand,Customer Strand,Top Genomic Sequence,Plus/Minus Strand,CNV Value,CNV Confidence
0,LL21170093,LL21170093,1,NaN,1_10673082,1,[T/C],0,1,8685608,A,B,T,C,A,G,T,C,A,G,0.380,0.447,2496,1502,0.827,0.552,0.8616,-0.1396,0.4981,0.8321,0.7921,BOT,BOT,NaN,-,NaN,NaN
1,LL21170093,LL21170093,1,NaN,1_10723065,2,[A/G],0,1,8754643,A,A,T,T,A,A,A,A,T,T,1.489,0.042,9357,168,1.532,0.018,0.8221,0.1112,0.0000,0.8042,1.0000,TOP,BOT,NaN,-,NaN,NaN
2,LL21170093,LL21170093,1,NaN,1_11407894,3,[A/G],0,1,9284239,A,A,A,A,A,A,A,A,A,A,1.440,0.025,9051,108,1.465,0.011,0.8538,0.2094,0.0000,0.8263,1.0000,TOP,TOP,NaN,+,NaN,NaN
3,LL21170093,LL21170093,1,NaN,1_11426075,4,[T/C],0,1,9302282,A,B,T,C,A,G,T,C,T,C,0.676,0.590,4334,1985,1.267,0.457,0.9097,0.0533,0.5421,0.8725,0.9806,BOT,BOT,NaN,+,NaN,NaN
4,LL21170093,LL21170093,1,NaN,1_13996200,5,[T/C],0,1,11952293,B,B,C,C,G,G,C,C,C,C,0.043,0.839,420,2806,0.882,0.967,0.8856,-0.1351,1.0000,0.8511,1.0000,BOT,BOT,NaN,+,NaN,NaN

In [47]:
df['SNP Name']

0    1_10673082
1    1_10723065
2    1_11407894
3    1_11426075
4    1_13996200
Name: SNP Name, dtype: object

In [33]:
df_allele1_top =df[['Sample ID', 'Allele1 - Top']]

In [36]:
df_allele1_top.set_index(['Sample ID'])

           Allele1 - Top
Sample ID
LL21170093             A
LL21170093             A
LL21170093             A
LL21170093             A
LL21170093             G

In [40]:
snp_list = [f'SNP{idx}' for idx in range(1, 6)]
snp_list

['SNP1', 'SNP2', 'SNP3', 'SNP4', 'SNP5']

In [49]:
snp_list = df['SNP Name']
snp_list

0    1_10673082
1    1_10723065
2    1_11407894
3    1_11426075
4    1_13996200
Name: SNP Name, dtype: object

In [50]:
index_list = [df['Sample ID'].values[0]]
index_list

['LL21170093']

In [51]:
# snp_list를 컬럼으로, Allele1 - Top 값을 갖는 (1, 5) 데이터프레임 생성
allele1_top_values = df['Allele1 - Top'].values[:5]
df_1x5 = pd.DataFrame([allele1_top_values], columns=snp_list, index=index_list)
df_1x5

SNP Name   1_10673082 1_10723065 1_11407894 1_11426075 1_13996200
LL21170093          A          A          A          A          G

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Sample ID             5 non-null      object
 1   Sample Name           5 non-null      object
 2   Sample Index          5 non-null      int64
 3   Sample Group          0 non-null      float64
 4   SNP Name              5 non-null      object
 5   SNP Index             5 non-null      int64
 6   SNP                   5 non-null      object
 7   SNP Aux               5 non-null      int64
 8   Chr                   5 non-null      int64
 9   Position              5 non-null      int64
 10  Allele1 - AB          5 non-null      object
 11  Allele2 - AB          5 non-null      object
 12  Allele1 - Forward     5 non-null      object
 13  Allele2 - Forward     5 non-null      object
 14  Allele1 - Top         5 non-null      object
 15  Allele2 - Top         5 non-null      object
 16  Allele1 - Design      5 non-null      object
 17  Allele2 - Design      5 non-null      object
 18  Allele1 - Plus        5 non-null      object
 19  Allele2 - Plus        5 non-null      object
 20  X                     5 non-null      float64
 21  Y                     5 non-null      float64
 22  X Raw                 5 non-null      int64
 23  Y Raw                 5 non-null      int64
 24  R                     5 non-null      float64
 25  Theta                 5 non-null      float64
 26  GC Score              5 non-null      float64
 27  Log R Ratio           5 non-null      float64
 28  B Allele Freq         5 non-null      float64
 29  GT Score              5 non-null      float64
 30  Cluster Sep           5 non-null      float64
 31  ILMN Strand           5 non-null      object
 32  Customer Strand       5 non-null      object
 33  Top Genomic Sequence  0 non-null      float64
 34  Plus/Minus Strand     5 non-null      object
 35  CNV Value             0 non-null      float64
 36  CNV Confidence        0 non-null      float64
dtypes: float64(13), int64(7), object(17)
memory usage: 1.6+ KB

In [22]:
df.shape

(5, 37)

In [25]:
df.set_index(['Sample ID', 'Allele1 - Top'], drop=True, inplace=True)

In [18]:
df

,Sample Name,Sample Index,Sample Group,SNP Name,SNP Index,SNP,SNP Aux,Chr,Position,Allele1 - AB,Allele2 - AB,Allele1 - Forward,Allele2 - Forward,Allele1 - Top,Allele2 - Top,Allele1 - Design,Allele2 - Design,Allele1 - Plus,Allele2 - Plus,X,Y,X Raw,Y Raw,R,Theta,GC Score,Log R Ratio,B Allele Freq,GT Score,Cluster Sep,ILMN Strand,Customer Strand,Top Genomic Sequence,Plus/Minus Strand,CNV Value,CNV Confidence
Sample ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
LL21170093,LL21170093,1,NaN,1_10673082,1,[T/C],0,1,8685608,A,B,T,C,A,G,T,C,A,G,0.380,0.447,2496,1502,0.827,0.552,0.8616,-0.1396,0.4981,0.8321,0.7921,BOT,BOT,NaN,-,NaN,NaN
LL21170093,LL21170093,1,NaN,1_10723065,2,[A/G],0,1,8754643,A,A,T,T,A,A,A,A,T,T,1.489,0.042,9357,168,1.532,0.018,0.8221,0.1112,0.0000,0.8042,1.0000,TOP,BOT,NaN,-,NaN,NaN
LL21170093,LL21170093,1,NaN,1_11407894,3,[A/G],0,1,9284239,A,A,A,A,A,A,A,A,A,A,1.440,0.025,9051,108,1.465,0.011,0.8538,0.2094,0.0000,0.8263,1.0000,TOP,TOP,NaN,+,NaN,NaN
LL21170093,LL21170093,1,NaN,1_11426075,4,[T/C],0,1,9302282,A,B,T,C,A,G,T,C,T,C,0.676,0.590,4334,1985,1.267,0.457,0.9097,0.0533,0.5421,0.8725,0.9806,BOT,BOT,NaN,+,NaN,NaN
LL21170093,LL21170093,1,NaN,1_13996200,5,[T/C],0,1,11952293,B,B,C,C,G,G,C,C,C,C,0.043,0.839,420,2806,0.882,0.967,0.8856,-0.1351,1.0000,0.8511,1.0000,BOT,BOT,NaN,+,NaN,NaN

In [26]:
df

                         Sample Name  Sample Index  Sample Group    SNP Name  \
Sample ID  Allele1 - Top
LL21170093 A              LL21170093             1           NaN  1_10673082
           A              LL21170093             1           NaN  1_10723065
           A              LL21170093             1           NaN  1_11407894
           A              LL21170093             1           NaN  1_11426075
           G              LL21170093             1           NaN  1_13996200

                          SNP Index    SNP  SNP Aux  Chr  Position  \
Sample ID  Allele1 - Top
LL21170093 A                      1  [T/C]        0    1   8685608
           A                      2  [A/G]        0    1   8754643
           A                      3  [A/G]        0    1   9284239
           A                      4  [T/C]        0    1   9302282
           G                      5  [T/C]        0    1  11952293

                         Allele1 - AB Allele2 - AB Allele1 - Forward  \
Sample ID  Allele1 - Top
LL21170093 A                        A            B                 T
           A                        A            A                 T
           A                        A            A                 A
           A                        A            B                 T
           G                        B            B                 C

                         Allele2 - Forward Allele2 - Top Allele1 - Design  \
Sample ID  Allele1 - Top
LL21170093 A                             C             G                T
           A                             T             A                A
           A                             A             A                A
           A                             C             G                T
           G                             C             G                C

                         Allele2 - Design Allele1 - Plus Allele2 - Plus  \
Sample ID  Allele1 - Top
LL21170093 A                            C              A              G
           A                            A              T              T
           A                            A              A              A
           A                            C              T              C
           G                            C              C              C

                              X      Y  X Raw  Y Raw      R  Theta  GC Score  \
Sample ID  Allele1 - Top
LL21170093 A              0.380  0.447   2496   1502  0.827  0.552    0.8616
           A              1.489  0.042   9357    168  1.532  0.018    0.8221
           A              1.440  0.025   9051    108  1.465  0.011    0.8538
           A              0.676  0.590   4334   1985  1.267  0.457    0.9097
           G              0.043  0.839    420   2806  0.882  0.967    0.8856

                          Log R Ratio  B Allele Freq  GT Score  Cluster Sep  \
Sample ID  Allele1 - Top
LL21170093 A                  -0.1396         0.4981    0.8321       0.7921
           A                   0.1112         0.0000    0.8042       1.0000
           A                   0.2094         0.0000    0.8263       1.0000
           A                   0.0533         0.5421    0.8725       0.9806
           G                  -0.1351         1.0000    0.8511       1.0000

                         ILMN Strand Customer Strand  Top Genomic Sequence  \
Sample ID  Allele1 - Top
LL21170093 A                     BOT             BOT                   NaN
           A                     TOP             BOT                   NaN
           A                     TOP             TOP                   NaN
           A                     BOT             BOT                   NaN
           G                     BOT             BOT                   NaN

                         Plus/Minus Strand  CNV Value  CNV Confidence
Sample ID  Allele1 - Top
LL21170093 A                             -        NaN             NaN
           A                             -        NaN             NaN
           A                             +        NaN             NaN
           A                             +        NaN             NaN
           G                             +        NaN             NaN

In [27]:
df.T

Sample ID             LL21170093                                      \
Allele1 - Top                  A           A           A           A
Sample Name           LL21170093  LL21170093  LL21170093  LL21170093
Sample Index                   1           1           1           1
Sample Group                 NaN         NaN         NaN         NaN
SNP Name              1_10673082  1_10723065  1_11407894  1_11426075
SNP Index                      1           2           3           4
SNP                        [T/C]       [A/G]       [A/G]       [T/C]
SNP Aux                        0           0           0           0
Chr                            1           1           1           1
Position                 8685608     8754643     9284239     9302282
Allele1 - AB                   A           A           A           A
Allele2 - AB                   B           A           A           B
Allele1 - Forward              T           T           A           T
Allele2 - Forward              C           T           A           C
Allele2 - Top                  G           A           A           G
Allele1 - Design               T           A           A           T
Allele2 - Design               C           A           A           C
Allele1 - Plus                 A           T           A           T
Allele2 - Plus                 G           T           A           C
X                           0.38       1.489        1.44       0.676
Y                          0.447       0.042       0.025        0.59
X Raw                       2496        9357        9051        4334
Y Raw                       1502         168         108        1985
R                          0.827       1.532       1.465       1.267
Theta                      0.552       0.018       0.011       0.457
GC Score                  0.8616      0.8221      0.8538      0.9097
Log R Ratio              -0.1396      0.1112      0.2094      0.0533
B Allele Freq             0.4981         0.0         0.0      0.5421
GT Score                  0.8321      0.8042      0.8263      0.8725
Cluster Sep               0.7921         1.0         1.0      0.9806
ILMN Strand                  BOT         TOP         TOP         BOT
Customer Strand              BOT         BOT         TOP         BOT
Top Genomic Sequence         NaN         NaN         NaN         NaN
Plus/Minus Strand              -           -           +           +
CNV Value                    NaN         NaN         NaN         NaN
CNV Confidence               NaN         NaN         NaN         NaN

Sample ID
Allele1 - Top                  G
Sample Name           LL21170093
Sample Index                   1
Sample Group                 NaN
SNP Name              1_13996200
SNP Index                      5
SNP                        [T/C]
SNP Aux                        0
Chr                            1
Position                11952293
Allele1 - AB                   B
Allele2 - AB                   B
Allele1 - Forward              C
Allele2 - Forward              C
Allele2 - Top                  G
Allele1 - Design               C
Allele2 - Design               C
Allele1 - Plus                 C
Allele2 - Plus                 C
X                          0.043
Y                          0.839
X Raw                        420
Y Raw                       2806
R                          0.882
Theta                      0.967
GC Score                  0.8856
Log R Ratio              -0.1351
B Allele Freq                1.0
GT Score                  0.8511
Cluster Sep                  1.0
ILMN Strand                  BOT
Customer Strand              BOT
Top Genomic Sequence         NaN
Plus/Minus Strand              +
CNV Value                    NaN
CNV Confidence               NaN